// Seed Dataset for SIH Prototype PS26024
// Fictional demonstration data with 5 Mines, 25+ Workers, Certificates, Violations, Actions, Alerts, Audit Logs.

export const DEMO_MINES = [
  {
    mineId: 'MINE-01',
    mineName: 'Demo Mine Alpha',
    location: 'Dhanbad Coalfield, Jharkhand',
    type: 'Underground & Opencast',
    status: 'ACTIVE',
    complianceScore: 88,
    riskLevel: 'LOW',
    officer: 'Sanjay Deshmukh (Mine Safety Officer)',
    officerId: 'officer01',
    workersCount: 8,
    activeViolations: 1,
    pendingActions: 1,
  },
  {
    mineId: 'MINE-02',
    mineName: 'Demo Mine Beta',
    location: 'Raniganj Basin, West Bengal',
    type: 'Opencast Mining',
    status: 'ACTIVE',
    complianceScore: 82,
    riskLevel: 'LOW',
    officer: 'Anil Sengupta (Safety Lead)',
    officerId: 'officer02',
    workersCount: 6,
    activeViolations: 2,
    pendingActions: 2,
  },
  {
    mineId: 'MINE-03',
    mineName: 'Demo Mine Gamma',
    location: 'Singrauli Coal Belt, Madhya Pradesh',
    type: 'Deep Underground Shaft',
    status: 'NEEDS_ATTENTION',
    complianceScore: 61,
    riskLevel: 'HIGH',
    officer: 'Rajesh Trivedi (Safety Officer)',
    officerId: 'officer03',
    workersCount: 7,
    activeViolations: 4,
    pendingActions: 3,
  },
  {
    mineId: 'MINE-04',
    mineName: 'Demo Mine Delta',
    location: 'Korba Industrial Belt, Chhattisgarh',
    type: 'Opencast Mechanized',
    status: 'ACTIVE',
    complianceScore: 91,
    riskLevel: 'LOW',
    officer: 'Kavita Raman (Mine Safety Manager)',
    officerId: 'officer04',
    workersCount: 5,
    activeViolations: 0,
    pendingActions: 0,
  },
  {
    mineId: 'MINE-05',
    mineName: 'Demo Mine Epsilon',
    location: 'Talcher Coalfields, Odisha',
    type: 'Underground Continuous Miner',
    status: 'ACTIVE',
    complianceScore: 73,
    riskLevel: 'MEDIUM',
    officer: 'Bikram Mohanty (Compliance Officer)',
    officerId: 'officer05',
    workersCount: 6,
    activeViolations: 2,
    pendingActions: 2,
  },
];

export const CERTIFICATE_CATEGORIES = [
  'Electrical Competency Certificate',
  'Mining Safety Training Certificate',
  'First Aid & Emergency Response Certificate',
  'Equipment Operation Certificate',
  'Fire Safety Certificate',
];

export const DEMO_WORKERS = [
  // Mine Alpha
  {
    workerId: 'W-10452',
    name: 'Rahul Patil',
    role: 'Licensed Electrician',
    mineId: 'MINE-01',
    area: 'Substation Zone 3',
    status: 'ACTIVE',
    joiningDate: '2023-04-15',
    bloodGroup: 'B+',
    contact: '+91 98765 43210',
  },
  {
    workerId: 'W-10453',
    name: 'Amit Sharma',
    role: 'Certified Blaster',
    mineId: 'MINE-01',
    area: 'Explosives Magazine & Face A',
    status: 'ACTIVE',
    joiningDate: '2022-08-10',
    bloodGroup: 'O+',
    contact: '+91 98765 43211',
  },
  {
    workerId: 'W-10454',
    name: 'Sameer Khan',
    role: 'Heavy Earth Moving Machinery (HEMM) Operator',
    mineId: 'MINE-01',
    area: 'Surface Quarry Pit 2',
    status: 'ACTIVE',
    joiningDate: '2021-11-20',
    bloodGroup: 'A+',
    contact: '+91 98765 43212',
  },
  {
    workerId: 'W-10455',
    name: 'Vikas Verma',
    role: 'Shift Safety Supervisor',
    mineId: 'MINE-01',
    area: 'Incline Shaft 1',
    status: 'ACTIVE',
    joiningDate: '2020-03-01',
    bloodGroup: 'AB+',
    contact: '+91 98765 43213',
  },
  {
    workerId: 'W-10456',
    name: 'Priya Nair',
    role: 'Ventilation & Gas Testing Technician',
    mineId: 'MINE-01',
    area: 'Airway Return Level 2',
    status: 'ACTIVE',
    joiningDate: '2023-09-05',
    bloodGroup: 'O-',
    contact: '+91 98765 43214',
  },
  {
    workerId: 'W-10457',
    name: 'Neha Singh',
    role: 'First Aid & Paramedic Officer',
    mineId: 'MINE-01',
    area: 'Surface Emergency Post',
    status: 'ACTIVE',
    joiningDate: '2022-01-18',
    bloodGroup: 'A-',
    contact: '+91 98765 43215',
  },

  // Mine Beta
  {
    workerId: 'W-20101',
    name: 'Rameshwar Mahato',
    role: 'Drill Operator',
    mineId: 'MINE-02',
    area: 'Opencast Bench 4',
    status: 'ACTIVE',
    joiningDate: '2022-05-12',
    bloodGroup: 'B+',
    contact: '+91 98765 43220',
  },
  {
    workerId: 'W-20102',
    name: 'Deepak Mondal',
    role: 'Industrial Electrician',
    mineId: 'MINE-02',
    area: 'Main Transformer Yard',
    status: 'ACTIVE',
    joiningDate: '2021-07-22',
    bloodGroup: 'O+',
    contact: '+91 98765 43221',
  },
  {
    workerId: 'W-20103',
    name: 'Suresh Soren',
    role: 'Dumper Operator',
    mineId: 'MINE-02',
    area: 'Haul Road Section C',
    status: 'ACTIVE',
    joiningDate: '2023-02-14',
    bloodGroup: 'AB+',
    contact: '+91 98765 43222',
  },

  // Mine Gamma (High Risk Mine)
  {
    workerId: 'W-30201',
    name: 'Kailash Prasad',
    role: 'Blasting Supervisor',
    mineId: 'MINE-03',
    area: 'Deep Seam IV Face',
    status: 'ACTIVE',
    joiningDate: '2019-10-15',
    bloodGroup: 'B-',
    contact: '+91 98765 43230',
  },
  {
    workerId: 'W-30202',
    name: 'Manoj Tiwari',
    role: 'Underground Winder Operator',
    mineId: 'MINE-03',
    area: 'Vertical Shaft Hoist House',
    status: 'ACTIVE',
    joiningDate: '2020-06-25',
    bloodGroup: 'A+',
    contact: '+91 98765 43231',
  },
  {
    workerId: 'W-30203',
    name: 'Rohan Gupta',
    role: 'Maintenance Fitter',
    mineId: 'MINE-03',
    area: 'Underground Conveyor Drive',
    status: 'ACTIVE',
    joiningDate: '2022-12-01',
    bloodGroup: 'O+',
    contact: '+91 98765 43232',
  },
  {
    workerId: 'W-30204',
    name: 'Dinesh Yadav',
    role: 'Electrical Substation Attendant',
    mineId: 'MINE-03',
    area: 'Underground Substation 2',
    status: 'ACTIVE',
    joiningDate: '2021-04-10',
    bloodGroup: 'B+',
    contact: '+91 98765 43233',
  },

  // Mine Delta
  {
    workerId: 'W-40301',
    name: 'Sunil Rathore',
    role: 'Continuous Miner Operator',
    mineId: 'MINE-04',
    area: 'Sector 5 Automated Panel',
    status: 'ACTIVE',
    joiningDate: '2021-03-15',
    bloodGroup: 'O+',
    contact: '+91 98765 43240',
  },
  {
    workerId: 'W-40302',
    name: 'Ananya Roy',
    role: 'Safety & Environmental Auditor',
    mineId: 'MINE-04',
    area: 'Central Safety Wing',
    status: 'ACTIVE',
    joiningDate: '2023-01-10',
    bloodGroup: 'A+',
    contact: '+91 98765 43241',
  },

  // Mine Epsilon
  {
    workerId: 'W-50401',
    name: 'Pradeep Behera',
    role: 'Roof Bolting Crew Lead',
    mineId: 'MINE-05',
    area: 'South Trunk Heading',
    status: 'ACTIVE',
    joiningDate: '2020-09-18',
    bloodGroup: 'B+',
    contact: '+91 98765 43250',
  },
  {
    workerId: 'W-50402',
    name: 'Santosh Swain',
    role: 'Haulage Locomotive Driver',
    mineId: 'MINE-05',
    area: 'Main Transport Incline',
    status: 'ACTIVE',
    joiningDate: '2022-04-20',
    bloodGroup: 'O-',
    contact: '+91 98765 43251',
  },
];

export const DEMO_CERTIFICATES = [
  // Rahul Patil (Key Demo: Expired Electrical Certificate)
  {
    certificateId: 'CERT-2024-0012',
    workerId: 'W-10452',
    workerName: 'Rahul Patil',
    certificateType: 'Electrical Competency Certificate',
    issueDate: '2024-08-15',
    expiryDate: '2026-08-15', // Passed -> Expired
    issuingAuthority: 'State Directorate of Electrical Safety (Demo)',
    documentUrl: 'DEMO_CERT_DOC_ELEC_01.pdf',
    verificationStatus: 'EXPIRED',
    mineId: 'MINE-01',
  },
  {
    certificateId: 'CERT-2025-0842',
    workerId: 'W-10452',
    workerName: 'Rahul Patil',
    certificateType: 'Mining Safety Training Certificate',
    issueDate: '2025-02-10',
    expiryDate: '2027-02-10', // Valid
    issuingAuthority: 'Mines Vocational Training Center (Demo)',
    documentUrl: 'DEMO_CERT_DOC_VTC_01.pdf',
    verificationStatus: 'VALID',
    mineId: 'MINE-01',
  },

  // Amit Sharma (Expiring soon example)
  {
    certificateId: 'CERT-2024-0991',
    workerId: 'W-10453',
    workerName: 'Amit Sharma',
    certificateType: 'Mining Safety Training Certificate',
    issueDate: '2024-09-10',
    expiryDate: '2026-09-10', // ~14 days left -> Expiring soon
    issuingAuthority: 'DGMS Approved Safety Cell (Demo)',
    documentUrl: 'DEMO_CERT_DOC_BLAST_01.pdf',
    verificationStatus: 'EXPIRING SOON',
    mineId: 'MINE-01',
  },
  {
    certificateId: 'CERT-2025-0105',
    workerId: 'W-10453',
    workerName: 'Amit Sharma',
    certificateType: 'First Aid & Emergency Response Certificate',
    issueDate: '2025-01-15',
    expiryDate: '2027-01-15',
    issuingAuthority: 'St. John Ambulance Association (Demo)',
    documentUrl: 'DEMO_CERT_DOC_FA_01.pdf',
    verificationStatus: 'VALID',
    mineId: 'MINE-01',
  },

  // Sameer Khan
  {
    certificateId: 'CERT-2025-0341',
    workerId: 'W-10454',
    workerName: 'Sameer Khan',
    certificateType: 'Equipment Operation Certificate',
    issueDate: '2025-03-20',
    expiryDate: '2027-03-20',
    issuingAuthority: 'Heavy Equipment Training Institute (Demo)',
    documentUrl: 'DEMO_CERT_DOC_HEMM_01.pdf',
    verificationStatus: 'VALID',
    mineId: 'MINE-01',
  },

  // Vikas Verma
  {
    certificateId: 'CERT-2024-0552',
    workerId: 'W-10455',
    workerName: 'Vikas Verma',
    certificateType: 'Fire Safety Certificate',
    issueDate: '2024-11-05',
    expiryDate: '2026-11-05',
    issuingAuthority: 'National Fire Safety Academy (Demo)',
    documentUrl: 'DEMO_CERT_DOC_FIRE_01.pdf',
    verificationStatus: 'VALID',
    mineId: 'MINE-01',
  },

  // Priya Nair
  {
    certificateId: 'CERT-2025-0720',
    workerId: 'W-10456',
    workerName: 'Priya Nair',
    certificateType: 'First Aid & Emergency Response Certificate',
    issueDate: '2025-05-12',
    expiryDate: '2027-05-12',
    issuingAuthority: 'Red Cross Society (Demo)',
    documentUrl: 'DEMO_CERT_DOC_FA_02.pdf',
    verificationStatus: 'VALID',
    mineId: 'MINE-01',
  },

  // Mine Gamma Workers (High Risk)
  {
    certificateId: 'CERT-2024-0089',
    workerId: 'W-30201',
    workerName: 'Kailash Prasad',
    certificateType: 'Mining Safety Training Certificate',
    issueDate: '2024-06-01',
    expiryDate: '2026-06-01', // Expired
    issuingAuthority: 'Mines Safety Council (Demo)',
    documentUrl: 'DEMO_CERT_DOC_BLAST_GAMMA.pdf',
    verificationStatus: 'EXPIRED',
    mineId: 'MINE-03',
  },
  {
    certificateId: 'CERT-2024-0412',
    workerId: 'W-30204',
    workerName: 'Dinesh Yadav',
    certificateType: 'Electrical Competency Certificate',
    issueDate: '2024-07-20',
    expiryDate: '2026-07-20', // Expired
    issuingAuthority: 'State Directorate of Electrical Safety (Demo)',
    documentUrl: 'DEMO_CERT_DOC_ELEC_GAMMA.pdf',
    verificationStatus: 'EXPIRED',
    mineId: 'MINE-03',
  },
];

export const DEMO_EQUIPMENT = [
  {
    equipmentId: 'EQ-101',
    name: 'Main Substation Transformer 33kV/3.3kV',
    type: 'High Voltage Electrical Substation',
    mineId: 'MINE-01',
    area: 'Substation Zone 3',
    inspectionStatus: 'REQUIRES_ATTENTION',
    lastInspection: '2026-08-10',
    nextInspection: '2026-09-10',
  },
  {
    equipmentId: 'EQ-102',
    name: 'HEMM Hydraulic Excavator (Cat 349D)',
    type: 'Excavation & Loading Machinery',
    mineId: 'MINE-01',
    area: 'Surface Quarry Pit 2',
    inspectionStatus: 'OPERATIONAL',
    lastInspection: '2026-08-20',
    nextInspection: '2026-09-20',
  },
  {
    equipmentId: 'EQ-301',
    name: 'Main Shaft Man-Winding Engine',
    type: 'Vertical Shaft Winder',
    mineId: 'MINE-03',
    area: 'Vertical Shaft Hoist House',
    inspectionStatus: 'CRITICAL_CHECK_NEEDED',
    lastInspection: '2026-07-28',
    nextInspection: '2026-08-28',
  },
];

export const DEMO_INSPECTIONS = [
  {
    inspectionId: 'INSP-2026-001',
    inspectorId: 'inspector01',
    inspectorName: 'Rajesh Kumar (Govt. Coal Mine Inspector)',
    mineId: 'MINE-01',
    mineName: 'Demo Mine Alpha',
    area: 'Substation Zone 3',
    date: '2026-08-26',
    inspectionType: 'Electrical & Personnel Compliance Safety Inspection',
    overallResult: 'FAILED',
    checklistResults: [
      { category: 'Safety & Signage', item: 'Danger High Voltage signage & isolation barriers in place', status: 'PASS', notes: 'Signboards clean and visible' },
      { category: 'Safety & Signage', item: 'Fire extinguishers inspected and charged', status: 'PASS', notes: 'CO2 cylinders within test date' },
      { category: 'Equipment Safety', item: 'Grounding & earth leakage protection verified', status: 'PASS', notes: 'Earth pit resistance 1.8 ohms' },
      { category: 'Equipment Safety', item: 'Insulation matting in front of HT breaker panels', status: 'PASS', notes: 'Tested 15kV grade' },
      { category: 'Worker Compliance', item: 'On-duty personnel possess valid Electrical Competency Certificate', status: 'FAIL', notes: 'Rahul Patil certificate CERT-2024-0012 expired on 15 Aug 2026' },
      { category: 'Worker Compliance', item: 'Mandatory PPE (insulated gloves, arc-flash face shield) worn', status: 'PASS', notes: 'PPE compliant' },
    ],
    notes: 'Substation equipment in sound condition; however, on-duty electrician certificate is expired, posing compliance breach under CEA Regulations.',
    evidence: 'evidence_substation_inspection_01.jpg',
    status: 'COMPLETED',
  },
  {
    inspectionId: 'INSP-2026-002',
    inspectorId: 'inspector01',
    inspectorName: 'Rajesh Kumar (Govt. Coal Mine Inspector)',
    mineId: 'MINE-01',
    mineName: 'Demo Mine Alpha',
    area: 'Incline Shaft 1',
    date: '2026-08-24',
    inspectionType: 'Roof Support & Haulage Track Audit',
    overallResult: 'PASSED',
    checklistResults: [
      { category: 'Safety & Signage', item: 'Man-riding signalling & emergency pull wires operational', status: 'PASS', notes: 'Trip switches tested' },
      { category: 'Equipment Safety', item: 'Rope haulage brake testing and clutch interlock', status: 'PASS', notes: 'Hydraulic pressure nominal' },
      { category: 'Worker Compliance', item: 'Supervisory staff valid competency certificates verified', status: 'PASS', notes: 'Vikas Verma certs valid' },
    ],
    notes: 'Incline haulage running smoothly. Regular greasing logged.',
    evidence: 'evidence_incline_haulage.jpg',
    status: 'COMPLETED',
  },
  {
    inspectionId: 'INSP-2026-003',
    inspectorId: 'inspector01',
    inspectorName: 'Rajesh Kumar (Govt. Coal Mine Inspector)',
    mineId: 'MINE-03',
    mineName: 'Demo Mine Gamma',
    area: 'Deep Seam IV Face',
    date: '2026-08-20',
    inspectionType: 'Ventilation & Gas Testing Audit',
    overallResult: 'FAILED',
    checklistResults: [
      { category: 'Safety & Signage', item: 'Methane and Carbon Monoxide continuous detectors operational', status: 'FAIL', notes: 'Sensor CH4-04 out of calibration' },
      { category: 'Worker Compliance', item: 'Blaster valid DGMS statutory competency certificate', status: 'FAIL', notes: 'Kailash Prasad training expired' },
    ],
    notes: 'Multiple severe non-compliances logged in Deep Seam IV face.',
    evidence: 'evidence_gamma_face.jpg',
    status: 'COMPLETED',
  }
];

export const DEMO_VIOLATIONS = [
  {
    violationId: 'VIO-2026-001',
    mineId: 'MINE-01',
    mineName: 'Demo Mine Alpha',
    area: 'Substation Zone 3',
    workerId: 'W-10452',
    workerName: 'Rahul Patil',
    certificateId: 'CERT-2024-0012',
    inspectionId: 'INSP-2026-001',
    category: 'Statutory Certification Breach',
    severity: 'HIGH',
    description: 'Electrician Rahul Patil assigned to High-Voltage 33kV substation with expired Electrical Competency Certificate (Expired: 15-Aug-2026).',
    evidence: 'evidence_cert_expired_rahul.png',
    reportedBy: 'Rajesh Kumar (Inspector INS-001)',
    date: '2026-08-26',
    status: 'OPEN', // Can transition to ACTION IN PROGRESS -> VERIFICATION REQUIRED -> RESOLVED
    riskScore: 86,
    riskLevel: 'HIGH',
    aiExplanation: 'High risk because the worker has an expired Electrical Competency Certificate while actively handling 33kV High-Voltage power equipment in Substation Zone 3.',
  },
  {
    violationId: 'VIO-2026-002',
    mineId: 'MINE-03',
    mineName: 'Demo Mine Gamma',
    area: 'Deep Seam IV Face',
    workerId: 'W-30201',
    workerName: 'Kailash Prasad',
    certificateId: 'CERT-2024-0089',
    inspectionId: 'INSP-2026-003',
    category: 'Explosives & Blasting Safety Non-Compliance',
    severity: 'CRITICAL',
    description: 'Blaster Kailash Prasad conducting underground shot-firing with expired Mining Safety certification and uncalibrated gas detector.',
    evidence: 'evidence_blasting_gamma.png',
    reportedBy: 'Rajesh Kumar (Inspector INS-001)',
    date: '2026-08-20',
    status: 'ACTION IN PROGRESS',
    riskScore: 94,
    riskLevel: 'HIGH',
    aiExplanation: 'Critical risk due to expired blasting competency in high-gas concentration zone combined with sensor calibration discrepancy.',
  },
  {
    violationId: 'VIO-2026-003',
    mineId: 'MINE-02',
    mineName: 'Demo Mine Beta',
    area: 'Haul Road Section C',
    workerId: 'W-20103',
    workerName: 'Suresh Soren',
    certificateId: null,
    inspectionId: 'INSP-2026-002',
    category: 'Equipment Maintenance Safety Defect',
    severity: 'MEDIUM',
    description: 'Rear reverse camera and audio warning siren malfunctioning on 50T Heavy Dumper D-08.',
    evidence: 'evidence_dumper_siren.jpg',
    reportedBy: 'Rajesh Kumar (Inspector INS-001)',
    date: '2026-08-22',
    status: 'RESOLVED',
    riskScore: 48,
    riskLevel: 'MEDIUM',
    aiExplanation: 'Moderate surface transport hazard resolved following auto-electrical harness replacement and supervisor sign-off.',
  }
];

export const DEMO_ALERTS = [
  {
    alertId: 'ALT-1001',
    type: 'VIOLATION_REPORTED',
    severity: 'HIGH',
    title: 'High-Severity Violation Reported in Substation Zone 3',
    description: 'Inspector INS-001 filed violation VIO-2026-001 regarding expired Electrical Competency Certificate for Rahul Patil.',
    relatedEntity: 'VIO-2026-001',
    mineId: 'MINE-01',
    createdDate: '2026-08-26T14:30:00Z',
    status: 'UNREAD',
    targetRoles: ['officer', 'management', 'authority'],
  },
  {
    alertId: 'ALT-1002',
    type: 'EXPIRY_WARNING',
    severity: 'MEDIUM',
    title: 'Certificate Expiring in 14 Days',
    description: 'Blaster Amit Sharma (W-10453) Mining Safety Certificate expires on 10-Sep-2026.',
    relatedEntity: 'CERT-2024-0991',
    mineId: 'MINE-01',
    createdDate: '2026-08-26T09:00:00Z',
    status: 'READ',
    targetRoles: ['officer'],
  },
  {
    alertId: 'ALT-1003',
    type: 'GOVERNANCE_WARNING',
    severity: 'HIGH',
    title: 'Mine Gamma Compliance Score Critical (61%)',
    description: 'Demo Mine Gamma has 4 unresolved high-severity violations. Corrective action velocity breached.',
    relatedEntity: 'MINE-03',
    mineId: 'MINE-03',
    createdDate: '2026-08-25T11:20:00Z',
    status: 'UNREAD',
    targetRoles: ['management', 'authority'],
  }
];

export const DEMO_CORRECTIVE_ACTIONS = [
  {
    actionId: 'CA-2026-001',
    violationId: 'VIO-2026-001',
    mineId: 'MINE-01',
    title: 'Obtain & Verify Renewed Electrical Competency Certification',
    description: 'Worker Rahul Patil must complete vocational refresher evaluation and submit renewed State Electrical Safety Competency Certificate.',
    assignedTo: 'Rahul Patil & Safety Desk',
    dueDate: '2026-08-30',
    priority: 'HIGH',
    status: 'PENDING', // PENDING -> IN PROGRESS -> COMPLETED -> VERIFICATION REQUIRED -> RESOLVED
    completionNotes: '',
    evidence: '',
    createdDate: '2026-08-26',
    resolvedDate: null,
  },
  {
    actionId: 'CA-2026-002',
    violationId: 'VIO-2026-002',
    mineId: 'MINE-03',
    title: 'Suspension of Shot-Firing & Recalibration of Environmental Sensors',
    description: 'Temporarily halt blasting face operations, recalibrate continuous methane monitors, and depute certified replacement blaster.',
    assignedTo: 'Mine Manager & Electrical Dept',
    dueDate: '2026-08-28',
    priority: 'CRITICAL',
    status: 'IN PROGRESS',
    completionNotes: 'Sensors recalibrated on 25-Aug. Replacement blaster deputed.',
    evidence: 'calib_report_face.pdf',
    createdDate: '2026-08-21',
    resolvedDate: null,
  },
  {
    actionId: 'CA-2026-003',
    violationId: 'VIO-2026-003',
    mineId: 'MINE-02',
    title: 'Replace HEMM Dumper Reverse Sensor & Warning Siren',
    description: 'Install replacement DGMS-compliant audio-visual reverse alarm on Dumper D-08.',
    assignedTo: 'Auto Electrical Workshop',
    dueDate: '2026-08-24',
    priority: 'MEDIUM',
    status: 'VERIFIED',
    completionNotes: 'New sealed waterproof siren unit installed and tested.',
    evidence: 'repair_work_order_08.pdf',
    createdDate: '2026-08-22',
    resolvedDate: '2026-08-24',
  }
];

export const DEMO_AUDIT_TRAIL = [
  {
    auditId: 'AUD-901',
    timestamp: '2026-08-26 14:32:10',
    actor: 'Inspector INS-001 (Rajesh Kumar)',
    role: 'Inspector',
    action: 'REPORT_VIOLATION',
    details: 'Logged Violation VIO-2026-001 for Mine Alpha regarding expired Electrical Competency Certificate (Rahul Patil). AI Risk Score: 86/100.',
    mineId: 'MINE-01',
  },
  {
    auditId: 'AUD-902',
    timestamp: '2026-08-26 14:30:00',
    actor: 'Inspector INS-001 (Rajesh Kumar)',
    role: 'Inspector',
    action: 'INSPECTION_SUBMITTED',
    details: 'Conducted safety inspection INSP-2026-001 in Substation Zone 3. Status: FAILED.',
    mineId: 'MINE-01',
  },
  {
    auditId: 'AUD-903',
    timestamp: '2026-08-24 16:45:00',
    actor: 'Inspector INS-001 (Rajesh Kumar)',
    role: 'Inspector',
    action: 'VERIFIED_CORRECTIVE_ACTION',
    details: 'Verified resolution for CA-2026-003 (Dumper audio siren repaired in Mine Beta). Marked VIO-2026-003 as RESOLVED.',
    mineId: 'MINE-02',
  },
  {
    auditId: 'AUD-904',
    timestamp: '2026-08-22 10:15:00',
    actor: 'Mine Officer OFF-002 (Anil Sengupta)',
    role: 'Mine Officer',
    action: 'CREATE_CORRECTIVE_ACTION',
    details: 'Assigned CA-2026-003 to Auto Electrical Workshop for Dumper D-08.',
    mineId: 'MINE-02',
  },
  {
    auditId: 'AUD-905',
    timestamp: '2026-08-20 18:00:00',
    actor: 'Regulatory Authority (DGMS Regional Director)',
    role: 'Regulatory Authority',
    action: 'ISSUE_DIRECTIVE',
    details: 'Issued Regulatory Notice DIR-2026-01 to Demo Mine Gamma regarding repetitive ventilation compliance lapses.',
    mineId: 'MINE-03',
  }
];

export const DEMO_ACCOUNTS = [
  {
    userId: 'inspector01',
    password: 'demo123',
    name: 'Rajesh Kumar',
    role: 'INSPECTOR',
    designation: 'Govt. Statutory Coal Mine Inspector',
    badge: 'INS-001',
    avatar: '👷‍♂️',
  },
  {
    userId: 'officer01',
    password: 'demo123',
    name: 'Sanjay Deshmukh',
    role: 'OFFICER',
    designation: 'Mine Safety & Compliance Officer',
    mineId: 'MINE-01',
    mineName: 'Demo Mine Alpha',
    badge: 'OFF-001',
    avatar: '🧑‍💼',
  },
  {
    userId: 'management01',
    password: 'demo123',
    name: 'Dr. V. K. Murthy',
    role: 'MANAGEMENT',
    designation: 'Director (Safety & Technical Operations)',
    badge: 'MGT-001',
    avatar: '🏢',
  },
  {
    userId: 'authority01',
    password: 'demo123',
    name: 'Dr. Arindam Sen',
    role: 'AUTHORITY',
    designation: 'Directorate General of Mines Safety (DGMS)',
    badge: 'DGMS-DIR',
    avatar: '🏛️',
  }
];
